# Nombre de la aplicación
spring.application.name=restaurant-backend

# Perfil activo por defecto
spring.profiles.active=local

# Hilos Virtuales activos de manera global para todos los perfiles
spring.threads.virtual.enabled=true

# Desactivar open-in-view por buenas prácticas de rendimiento
spring.jpa.open-in-view=false

# Ubicación común de las migraciones
spring.flyway.locations=classpath:db/migration

# Configuración de base de datos base con variables de entorno
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/platolisto}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Seguridad (JWT)
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

# Configuración de CORS
application.security.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}

# Monitoreo (Spring Boot Actuator)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
