# ----------------------------------------------------
# PERFIL: PROD (Producción)
# ----------------------------------------------------

# Configuración de Base de Datos para Producción (Obligatorio por Variables de Entorno)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate (Producción: Validar estrictamente, ocultar SQL de consola)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Flyway Producción
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false -- Evitar baselines automáticos en producción por seguridad
spring.flyway.baseline-version=0
